### ISSUE TITLE
SAM doesn't see some modifications.

### ISSUE THREAD

**Issue by ghost** [PaulCombal/SamRewritten-legacy#50]
For example Estranged: Act I, this is a free modification for HL2.

![image](https://user-images.githubusercontent.com/50836710/72513710-6e7d2d00-385e-11ea-8b03-3e337ef05271.png)
![image](https://user-images.githubusercontent.com/50836710/72513727-78069500-385e-11ea-82e1-511f742e953d.png)

**Comment by PaulCombal** [comment]
Yes, that's true, that's because the game list is retrieved from another of my projects here https://github.com/PaulCombal/SteamAppsList . For now, the only shown apps on SamRewritten are the ones categorized as "game" and have achievements.

Thanks for the report, I'll try to fix that when I will have time.

In the meantime I believe typing in the AppId of the app you want to launch should do the trick.

**Comment by ghost** [comment]
Yeah, thanks you for answer.

![image](https://user-images.githubusercontent.com/50836710/72518579-b607b700-3866-11ea-9160-1983362afbc0.png)

![image](https://user-images.githubusercontent.com/50836710/72518645-d9326680-3866-11ea-9ebc-b24ab58efc8a.png)

**Comment by wgpierce** [comment]
@PaulCombal what's the fix here? Is it implementing the settings window to allow seeing all apps? Manually typing in the app ID has been a good enough workaround for a while.

We can't do much if the game has achievements despite the store page saying it doesn't have them, unless we maintain a manual list like the original SAM.

**Comment by PaulCombal** [comment]
I think the fix here would be to change the "SteamAppsDumps" to also include mods. That's the cleanest I can think of, and the way it should be imo.

**Comment by wgpierce** [comment]
This is the same issue as https://github.com/PaulCombal/SamRewritten/issues/41 as per https://github.com/PaulCombal/SamRewritten/issues/41#issuecomment-629879122.
