### ISSUE TITLE
Why many games doesn't appear on SAM?

### ISSUE THREAD

**Issue by felixsanz** [PaulCombal/SamRewritten-legacy#52]
Sorry if this has been answered, i've been looking and i couldn't find an answer.

I own many games that doesn't appear on SAM. Is there any reason for that?

**Comment by PaulCombal** [comment]
Yes, when a game is removed in the store, it will not be detected by SAM anymore. 
Also, the newest apps might not be available because I'm too lazy to update the app database, I'll try to update it soon.

Also, you can launch any game you own regardless if it was removed entering its appid.
You can get the appid from the store page URL, for example for csgo: `https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/` the appid is 730. You can type the appid in SamRewritten's search bar and it'll give you an option for it.

Would that solve your issue? If so I'll try to make that clearer

**Comment by felixsanz** [comment]
that's awesome! thanks so much!
