### ISSUE TITLE
Achievements are locked but the steam stats stay the same

### ISSUE THREAD

**Issue by broccoli-is-healthy** [PaulCombal/SamRewritten-legacy#69]
About the "steam stats" I'm talking about the achievement showcase on your steam profile. I have 3679 achievements across 54 games. I locked 30+ achievements from 6 games, they won't load when I try to add them to the showcase, but the games do still appear in the list, and the stats stay the same (3679 achievements - 54 games). 

Is this just how it is?

**Comment by wgpierce** [comment]
Yeah I think it's controlled on the Steam server side, can't do much about it AFAIK.

Same with your average completion rate, even if you re-lock achievements, it doesn't affect your average completion rate. So trying to relock all achievements on a game to try to remove it from affecting your average completion rate (because games with 0 achievements unlocked do not affect average completion rate) won't work either.

**Comment by broccoli-is-healthy** [comment]
That sucks, I kinda suspected it. Thanks for confirming it.
