### ISSUE TITLE
Crusader Kings III missing

### ISSUE THREAD

**Issue by vfauth** [PaulCombal/SamRewritten-legacy#92]
Hi,

I just noticed CKIII does not appear in the games list, even though I own it and it is installed (and has been for months).

And thank you for the software !

**Comment by PaulCombal** [comment]
Last time we updated the game list was maybe a year ago, so that makes sense. I don't know exactly when I'll update the list, in the meantime you can type the Steam App Id of the game in the search bar to access it.

If you want to update the game list by yourself, feel free to use [this repo](https://github.com/PaulCombal/SteamAppsList) and open a PR for [this repo](https://github.com/PaulCombal/SteamAppsListDumps).

**Comment by vfauth** [comment]
I thought the game list was dynamic, but that makes sense now!
I'll use the app ID, it's easy enough.

Thank you for the explanation, and sorry for the useless issue then :)

**Comment by wgpierce** [comment]
There's actually a lurking bug where one of the steam app_id's returns nothing at all, and that trips up the script. I'll fix it this weekend and update the list.

**Comment by wgpierce** [comment]
The list is now updated. @vfauth please retry.
Delete $HOME/.cache/SamRewritten/game_list.json or $XDG_CACHE_DIR/game_list.json if it's set to force a refresh.
I PR'd the fix for URLs returning nothing at https://github.com/PaulCombal/SteamAppsList/pull/3

**Comment by vfauth** [comment]
It's still not there :/
What I did:
- Rebuild the package from Git (I am using this: https://aur.archlinux.org/packages/samrewritten-git)
- Cleared the cache ($HOME/.cache/SamRewritten/game_list.json)

However, I can confirm it is in the SteamAppsList dump repo.
